architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  sudo apt-get update
  curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  sudo apt-get install -y nodejs                                     # Install Node
  sudo apt-get install jq                                            # For JSON cli parsing.
  node --version
  npm --version
  npm install
decrypt:
  deployment.txt: "repo/dcfg/deployment.txt.asc"
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    chmod +x ./deploy.sh
    ./deploy.sh
release:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    chmod +x ./deploy.sh
    ./deploy.sh
