architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  sudo apt-get update
  whereis npm
  curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  sudo apt-get install -y nodejs
  sudo apt-get install jq
  npm install
  ./node_modules/.bin/webpack --version
decrypt:
  deployment.txt: "repo/dcfg/deployment.txt.asc"
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    chmod +x ./deploy.sh
    ./deploy.sh
release:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    chmod +x ./deploy.sh
    ./deploy.sh
