language: node_js
node_js:
- 9
cache:
  directories:
  - node_modules
before_install:
- npm install npm@latest -g
- npm install webpack@latest -g
- npm -v
- webpack --version
- npm install
script:
- NODE_ENV=production webpack
